version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:80"  

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend

