# Generated by Django 4.1.7 on 2023-02-15 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_simulationserializer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimulationSerializer',
        ),
        migrations.AddField(
            model_name='simulation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
