# Generated by Django 4.2.1 on 2023-06-05 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_r_h_simulation_total_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.simulation')),
            ],
        ),
    ]
