# Generated by Django 4.2.1 on 2023-06-09 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='advertise_interval',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='center_node_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='generation_interval',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='heartbeat_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='network_transmit_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='ntis',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='random_nodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='relay_retransmit_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='rris',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='scan_interval',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simulation',
            name='scan_window',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='main.simulation'),
        ),
    ]
