# Generated by Django 4.2.1 on 2023-06-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_simulation_advertise_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='run_log',
            field=models.TextField(null=True),
        ),
    ]
