# Generated by Django 4.2.4 on 2023-08-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_simulation_run_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
