# Generated by Django 4.2.4 on 2023-08-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_simulation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='preview',
            field=models.TextField(null=True),
        ),
    ]
