# Generated by Django 4.2.4 on 2023-08-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_simulation_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='node_range',
            field=models.FloatField(),
        ),
    ]
